export const PRODUCTS_DISPLAY = 'PRODUCTS::DISPLAY';
    export const ON_PRODUCTS_FETCHING = 'PRODUCTS::FETCHING';
    export const ON_PRODUCTS_FETCHED = 'PRODUCTS::FETCHED';
    export const ON_PRODUCTS_FETCH_ERROR = 'PRODUCTS::FETCH_ERROR';

export const SUBMIT_FORM = 'FORM_SUBMITING'
    export const ON_FORM_SUBMITED = 'FORM::SUBMITED'
    export const ON_FORM_SUBMIT_ERROR = 'FORM::SUBMIT_ERROR'
    export const ON_EMPTY_FORM_STATE = 'FORM::CLEAR_STATE'