export const PRODUCTS_DISPLAY = 'PRODUCTS::DISPLAY';
    export const ON_PRODUCTS_FETCHING = 'PRODUCTS::FETCHING';
    export const ON_PRODUCTS_FETCHED = 'PRODUCTS::FETCHED';
    export const ON_PRODUCTS_FETCH_ERROR = 'PRODUCTS::FETCH_ERROR';
